### PR TITLE
Update funkit version to 2.0.11

### PR DESCRIPTION
**Pull request by chloe-tan**
1. Fixes ESM build issue in ion app as seen in versions 2.0.5 - 2.0.7
2. Fixes edge case where users' assets on `Scroll` would break the checkout UI

### CODE REVIEW

**Comment by knoll3** [comment]
@chloe-tan I'm getting an issue here on v2.0.10 where the network no longer appear in the network selector. 
Here is what we expect to see (v2.0.4):
image

Here is what we are getting (v.2.0.10):
image

**Comment by chloe-tan** [comment]
> @chloe-tan I'm getting an issue here on v2.0.10 where the network no longer appear in the network selector. Here is what we expect to see (v2.0.4): image
> 
> Here is what we are getting (v.2.0.10): image

Bumped our package version. Should be resolved now

Screenshot 2024-09-12 at 2 23 05 AM

**Comment by knoll3** [comment]
> > @chloe-tan I'm getting an issue here on v2.0.10 where the network no longer appear in the network selector. Here is what we expect to see (v2.0.4)
> 
> Thanks for catching this. Bumped our package version. Should be resolved now
> 
> Screenshot 2024-09-12 at 2 23 05 AM

Thanks! This works on my end as well.

**Comment by knoll3** [comment]
I am closing this PR since the funkit version update is being handled in a different PR. https://github.com/Ion-Protocol/nucleus-app/pull/19

**Pull request closed without merging**
